### PR TITLE
updates to README including correction to function name (nist_ri()) a…

### PR DESCRIPTION
**Pull request by Aariq**
I was just trying to do some minor updates to the README, although for some reason the ChEBI additions are showing up as new.  Maybe I'm doing the PR to the wrong branch?  If this doesn't work, I can try again later.

### CODE REVIEW

**Comment by andreasLD** [comment]
I was also about to make some changes to README.Rmd. E.g. removing deprecated ChemSpider functions and adding my name. Don't know why the ChEBI text in your PR is marked as new. The branch seems ok.

**Comment by EDiLD** [comment]
@Aariq looks like you just need to rebase your branch:
 https://github.com/ropensci/webchem/network

As you deviated from master quite a while ago...

**Comment by EDiLD** [comment]
@andreasLD & @Aariq don't be afraid of conflicts. You can deal with them ;)

**Comment by Aariq** [comment]
Dang, I thought I rebased correctly, but apparently not.  I'll give it another try later today if I have time.

**Comment by Aariq** [comment]
Ok, I think maybe it's fixed? Sorry this is a bit messy.  This PR actually does a few things:

1. Finishes fixing a bug where `NA` was mistaken for sodium and adds a test. #158 #161 
2. Updates NEWS with bug fix.
3. Updates link to ChemSpider API in README.Rmd
4. Fixes mistake in function name in README.Rmd (`get_ri()` instead of `nist_ri()`)
5. Adds example for `nist_ri()` to README.Rmd
6. Fixes a couple minor formatting things in README.Rmd

**Comment by Aariq** [comment]
It looks like the AppVeyor error is a Windows bug? 

```
> myRIs <- nist_ri(c("78-70-6", "873-94-9", "13474-59-4"), "linear", "non-polar", "ramp")
Error in open.connection(x, "rb") : 
  schannel: next InitializeSecurityContext failed: SEC_E_BUFFER_TOO_SMALL (0x80090321) - The buffers supplied to a function was too small.
Calls: nist_ri ... get_ri_xml -> read_html_slow -> <Anonymous> -> read_html.default
Execution halted

```

https://github.com/ropensci/rcrossref/issues/155#issuecomment-412158362

**Comment by stitam** [comment]
I fetched your pull request, tested cir_query() manually (works as intended), also R CMD check succeeded. However, running this example produced a warning:

`myRIs <- nist_ri(c("78-70-6", "873-94-9", "13474-59-4"), "linear", "non-polar", "ramp")
Warning message:
In get_ri_xml(., type, polarity, temp_prog) :
  There are no RIs for CAS# 873-94-9 of type LINEAR-RI-NON-POLAR-RAMP. Returning NA.`

Is it possible that this is causing the Appveyor build error?

**Comment by Aariq** [comment]
Possibly? I think I had included that CAS# on purpose to show that it returns NA if it can't find an RI for a particular CAS#. I can try changing the example to \dontrun{}

**Comment by Aariq** [comment]
Ok, well, fixed the SEC_E_BUFFER_TOO_SMALL error, but now it's failing because it can't install tibble??

**Comment by stitam** [comment]
Thanks @Aariq for the fix! I am merging the pull request.

**Pull request merged**
