### PR TITLE
added check for NA in get_cid()

### PR DESCRIPTION
**Pull request by Dahaniel**

### CODE REVIEW

**Comment by EDiLD** [comment]
Thanks Daniel! I suspect, this will be also the case for `get_csid()` and other functions? Need to check... #12

**Comment by Dahaniel** [comment]
Probably, but as I only used get_cid() and cir_query() I only recognized it there.

**Comment by EDiLD** [comment]
Fixed also in other functions. Now there is also documentation for bulk processing.

**Comment by Dahaniel** [comment]
great!

**Pull request merged**
