### PR TITLE
Upgrade get_csid() to accept more input types, etc.

### PR DESCRIPTION
**Pull request by stitam**
* `get_csid()` now accepts `name`, `formula`, `inchi`, `inchikey`, `smiles`. Default is `name`.
* `get_csid()` now returns a data frame, and not a named list. `csid` is the first column.
* `cs_convert()` now returns vectors.
* Style was updated as recommended by `lintr::lint()`
* There was a typo in `cs_check_key()`, `option->options`, also added some more detail.

PR task list:
- [x] Update NEWS
- [x] Add tests (if appropriate)
- [x] Update documentation with `devtools::document()`
- [x] Check package passed

### CODE REVIEW

**Comment by stitam** [comment]
This PR is related to Issue #191, Issue #193, Issue #206, Issue #207.

**Comment by stitam** [comment]
I think it would be better not to export the `cs_*_csid()` functions, only the top level functions that use them, `get_csid()` and `cs_convert()`. I think it helps with ease of use, as it provides a single function to get a csid from all sorts of query types and another to convert between all sorts of id types. Are you suggesting that we shouldn't create `roxygen2` documentation for non exported functions? I don't have a strong opinion on this. The documentation was meant for future developers. Do we expose a documentation if we don't export the function itself?

**Comment by Aariq** [comment]
If the documentation is for developers only, then I wouldn't create the .Rd file.  You can add a @noRd to keep the roxygen2 comments in the .R file, but not generate a help page.  I've been meaning to do this for a couple of other functions as well. #199

**Comment by stitam** [comment]
You are right, we have already discussed this, thanks! I will update this PR.

**Pull request merged**
