### PR TITLE
pc_synonyms multiple compounds per request

### PR DESCRIPTION
**Pull request by damondpham**
In this new version, `pc_synonyms` will submit `CHUNKSIZE` compounds per request, instead of one per request. This should be faster.

This is my first pull request so I apologize for any mistakes; hopefully this is helpful!

### CODE REVIEW

**Comment by Aariq** [comment]
I get an error using this version of pc_synonyms "Error in names(object) <- nm : 
  'names' attribute [11] must be the same length as the vector [2]"

**Comment by EDiLD** [comment]
@damondpham Thanks for your contribution! I am currently busy with work and can't handle this at the moment, earliest in two weeks (volunteers, welcome - I'll grant full access to responsible contributors).

Can you adress the points raised by @Aariq (and @Aariq can you provide an reproducible example?).

Note that I have unit tests defined for most functions. You can find them in the `tests` branch. Simple merge your changes into this branch and run the tests and link results here  (I separated tests from master, as I don't want the tests be run on each push - being nice to the servers).

**Comment by damondpham** [comment]
I fixed the error, and within two weeks I can run those tests.

I realized one downside with submitting multiple chemicals per request is that, if the request fails because of one chemical, all chemicals will get a NA result. I think this can be fixed by re-trying in the case of failure, but submitting one chemical per request instead of all as a group.

**Comment by EDiLD** [comment]
>  and within two weeks I can run those tests.

Great! 

You can also run only the pc_* tests locally...

**Comment by damondpham** [comment]
I'm actually not sure how to run the tests and link my results here nicely. What kind of files would I submit?

I did run the four test cases for pc_synonyms locally, and they all passed. This is the only function I changed.

**Comment by stitam** [comment]
Thank you @damondpham for your contribution!

Given that:
* The checks are still failing
* The source repo has probably been deleted
* There has been no activity on this PR in the past 1.5 years

I think it is safe to assume that this PR has been abandoned. I am sorry we couldn't merge it, I really hope we will see more contributions from you in the future! I am closing this pull request.

**Pull request closed without merging**
