### PR TITLE
Pubchem improvements

### PR DESCRIPTION
**Pull request by jranke**

### CODE REVIEW

**Comment by EDiLD** [comment]
OK, maybe they bought better servers. My information of 3/sec might be outdated.

**Comment by EDiLD** [comment]
Pull request is on master, all tests are passing [Note I test manually on a separate branch, to avoid unnecessary load on the servers]. Thanks for your contribution! Will you be @SETAC Brussels next year? I will show a poster on webchem, maybe I could also integrate chents as an example? Find this really interesting (also because i've never used R6 before).

**Comment by jranke** [comment]
Cool! Yes, I will be in Brussels! I am 
giving a talk on bioicides, and in 
fact I am using chents/webchem in 
the project to explore the 
possibilities. I would be happy to 
contribute something if it makes 
sense.

**Comment by EDiLD** [comment]
Cool! I'll come back to you in after my phd defense in February...

**Pull request merged**
