### PR TITLE
Good Scents scraper

### PR DESCRIPTION
**Pull request by jmorim**
Added tgsc_percept(), a function similar to fn_percept() except it uses aromas from The Good Scents Company.

```r
tgsc_percept('122-78-1')
```

PR task list:
- [X ] Update NEWS
- [X] Add tests (if appropriate)
- [X] Update documentation with `devtools::document()`
- [X] Check package passed (it didn't because of get_csid())

### CODE REVIEW

**Comment by EDiLD** [comment]
Thank you for the PR!

Can you rebase on top of the current master? something along these lines 

```
git remote add upstream (url-for-upstream-repository) 
git fetch upstream 
git rebase upstream/master
 git push -f origin
 (do new pull request on website)
```

Because your PR includes >100 commits from myself... Then I can readily merge this.

**Comment by EDiLD** [comment]
Merged! 
Thanks for your contribution!

If you want, you can add yourself as contributor to the `DESCRIPTION` file and the README (in a second PR).

**Comment by jmorim** [comment]
This seems to have never been added, should I make a new pull request?

**Comment by Aariq** [comment]
Huh, you're right.  Yeah, if you could rebase and make a new PR that would be great.  Sorry about that!  Are you relatively sure that Good Scents Company is OK with scraping?

**Comment by jmorim** [comment]
I'm not sure about the ethics of scraping, I'll contact the site admin.

**Comment by Aariq** [comment]
It would be an amazing addition to webchem if they're ok with scraping of flavor percepts.

**Pull request closed without merging**
