### PR TITLE
Webchem sleep function

### PR DESCRIPTION
**Pull request by andschar**
Here's the PR for a single function to sleep them all ;)
After #287. Let me know what you think.

### CODE REVIEW

**Comment by andschar** [comment]
hm, don't really see what s happening here.

**Comment by stitam** [comment]
> hm, don't really see what s happening here.

Tests work locally..

**Comment by stitam** [comment]
So the tests seem to fail consistently for `cir`. Could it be because of the reduced wait times? I am now wondering if we should include this PR in v1.1. Maybe it would be worth to keep it in a dev version for a while to see if any other functions misbehave?

**Comment by andschar** [comment]
> Maybe it would be worth to keep it in a dev version for a while to see if any other functions misbehave?

I agree let's wait a bit since this effects every function!

**Pull request merged**
