### PR TITLE
Final edits before v1.1

### PR DESCRIPTION
**Pull request by stitam**
* Added a startup message that points to the survey, let me know if you like it.
* Removed authors from function documentation, if any authors have an issue with this, we can revert later.
* Removed contributors from NEWS.md, if any contributors have an issue with this, we can revert later.

Any other quick fixes before we release v1.1?

### CODE REVIEW

**Comment by andschar** [comment]
Should we also include the wait time function from #287? I could file a PR for that and we have had a look at all the web services  concerning their policies, though mostly without finding anything.

**Comment by stitam** [comment]
> Should we also include the wait time function from #287? I could file a PR for that and we have had a look at all the web services concerning their policies, though mostly without finding anything.

Yeah, if you're almost ready with it, then sure, let's put it in. I'll merge this PR last so it is really "final edits":)

**Comment by andschar** [comment]
I have created PR #300

**Comment by stitam** [comment]
> I have created PR #300

Just flagging within that we have agreed within the PR discussion that we'll not include this PR in v1.1.

**Pull request merged**
